/* Main.ino f,ki m                                                                                    mmmmmmmmmmmmmmmmile generated by New Project wizard
 *
 * Created:   Mon May 4 2020
 * Processor: Arduino Uno
 * Compiler:  Arduino AVR
 */
#include <Nokia_LCD.h>
#include <DHT.h>
#include <Adafruit_Sensor.h>
#include <SoftwareSerial.h>

#define MQ2pin (A0)
#define DHTpin (8)
#define DHTType DHT22

Nokia_LCD lcd(3 /* CLK */, 4 /* DIN */, 5 /* DC */, 7 /* CE */, 6 /* RST */);
DHT dht(DHTpin,DHTType);
float gasValue;

int hum=dht.readHumidity();
int temp=dht.readTemperature();

const int buzzer=9;
const int ledPin=13;
const int buttonPin=A2;
int buttonState = 0;

unsigned long startTime = 0;
unsigned long intervalTime = 20000UL; //2 minutes

void setup(){
pinMode(buzzer, OUTPUT);
pinMode(ledPin, OUTPUT);
pinMode(buttonPin, INPUT);

gasValue = analogRead(MQ2pin);

dht.begin();
lcd.begin();
lcd.clear();
  lcd.setCursor(30, 0);
   lcd.println("MONITOR");
   lcd.setCursor(0, 1);
  lcd.print("GasLevel: ");
   lcd.print(gasValue);
   lcd.setCursor(0,3);
  lcd.print("Humidity: ");
   lcd.print(hum);
    lcd.print(" %");
    lcd.setCursor(0,5);
  lcd.print("Temp: ");
   lcd.print(temp);
    lcd.print("*C");

    if(gasValue>300){  
digitalWrite(ledPin, HIGH);
    tone(buzzer,1000);
}
if(temp<20 || temp>48){
 digitalWrite(ledPin, HIGH);
     tone(buzzer,1000);
}
    }

void loop(){
buttonState = digitalRead(buttonPin);
//if button is pressed
 if (buttonState == HIGH){
    // turn LED and buzzer off :
    digitalWrite(ledPin, LOW);
      noTone(buzzer);
  } 
  //if buzzer rings for more than 2minutes
  if ((buttonState == LOW) && (digitalRead(ledPin) == HIGH) && (millis()-startTime>intervalTime)){
    lcd.clear();//write code for gsm and turning on gps
  lcd.setCursor(0,3);
  lcd.print("turn on gps ,send sms");
  
  }
}